const plants = [
    {
        id: 1,
        name: "Jacinto",
        sciName: "Hyacinthus",
        description: "Magia floral en casa. Colores y fragancia cautivadores. Belleza fácil de cuidar. Eleva tu espacio.",
        lm: "Luz directa",
        size: "Chica",
        price: 2399,
        image: "../assets/img/plants/jacinto.png",
        quantity: 1
    },
    {
        id: 2,
        name: "Rosal",
        sciName: "Rosa",
        description: "Belleza que perdura. Elegancia atemporal. Amor en cada pétalo. Transforma tu entorno.",
        lm: "Luz directa",
        size: "Grande",
        price: 4899,
        image: "../assets/img/plants/rosas.jpg",
        quantity: 1
    },
    {
        id: 3,
        name: "Veraneras",
        sciName: "Bougainvillea",
        description: "Colores del verano todo el año. Frescura y alegría en cada flor. Naturaleza radiante en tu espacio. Vive el verano siempre.",
        lm: "Luz directa",
        size: "Grande",
        price: 3599,
        image: "../assets/img/plants/veranera.webp",
        quantity: 1
    },
    {
        id: 4,
        name: "Begonia",
        sciName: "Begonia elatior",
        description: "Color y encanto en un solo lugar. Elegancia natural que florece. Transforma tu espacio con su belleza única. Vive la belleza de la begonia.",
        lm: "Semi-sombra",
        size: "Mediana",
        price: 2499,
        image: "../assets/img/plants/begonia.webp",
        quantity: 1
    },
    {
        id: 5,
        name: "Azalea",
        sciName: "Azalea japonica",
        description: "Estallido de colores en tu entorno. Elegancia efímera que perdura. Transforma tu espacio con su encanto floral. Disfruta de las azaleas.",
        lm: "Semi-sombra",
        size: "Mediana",
        price: 6199,
        image: "../assets/img/plants/azalea.jpg",
        quantity: 1
    },
    {
        id: 6,
        name: "Petunia",
        sciName: "Petunia hybrida",
        description: "Paleta de colores vivos que dan vida. Elegancia floral que perdura. Transforma tu espacio con su encanto natural. Sumérgete en la inspiración de las petunias.",
        lm: "Semi-sombra",
        size: "Chica",
        price: 4499,
        image: "../assets/img/plants/petunia.jpg",
        quantity: 1
    },
    {
        id: 7,
        name: "Astilbe",
        sciName: "Astilbe x arendsii",
        description: "Plumas de elegancia que perduran. Belleza natural transformadora. Infunde tu espacio con su encanto único. Sumérgete en el mundo de las astilbes.",
        lm: "Semi-sombra",
        size: "Mediana",
        price: 1999,
        image: "../assets/img/plants/astilbe.jpg",
        quantity: 1
    },
    {
        id: 8,
        name: "Planta araña",
        sciName: "Chlorophytum comosum",
        description: "Hojas de encanto duradero. Belleza natural en transformación. Infunde tu entorno con su singularidad. Adéntrate en el mundo de las Planta Araña.",
        lm: "Sombra",
        size: "Mediana",
        price: 1899,
        image: "../assets/img/plants/planta-ara.jpg",
        quantity: 1
    },
    {
        id: 9,
        name: "Lirio de la Paz",
        sciName: "Spathiphyllum",
        description: "Paz en cada pétalo. Belleza natural que transforma. Llena tu espacio con su gracia única. Adéntrate en el mundo del Lirio de la Paz",
        lm: "Sombra",
        size: "Mediana",
        price: 3199,
        image: "../assets/img/plants/lirio-de-la-paz.jpeg",
        quantity: 1
    },
    {
        id: 10,
        name: "Calathea",
        sciName: "Marantaceae",
        description: "Pinceladas de elegancia que cambian constantemente. Belleza natural en transformación. Llena tu espacio con su encanto único. Sumérgete en el mundo de las Calatheas.",
        lm: "Sombra",
        size: "Grande",
        price: 5349,
        image: "../assets/img/plants/calathea.webp",
        quantity: 1
    },
    {
        id: 11,
        name: "Helecho de Maidenhair",
        sciName: "Adiantum raddianum",
        description: "Explosión de follaje espumoso. Belleza natural en constante transformación. Infunde tu espacio con su encanto único. Adéntrate en el mundo de los Helechos de Maidenhair.",
        lm: "Sombra",
        size: "Grande",
        price: 4799,
        image: "../assets/img/plants/helecho-de-maidenhair.jpg",
        quantity: 1
    },
    {
        id: 12,
        name: "Árbol de Jade",
        sciName: "Crassula ovata",
        description: "Luminosidad que trasciende. Belleza natural en continua metamorfosis. Colma tu espacio con su encanto singular. Explora el intrigante universo de los Árboles de Jade.",
        lm: "Sombra",
        size: "Chica",
        price: 1199,
        image: "../assets/img/plants/arbol-de-jade.jpg",
        quantity: 1
    },
    {
        id: 13,
        name: "Filodendro de hoja de corazón",
        sciName: "Philodendron scandens",
        description: "Vitalidad en constante latir. Belleza natural en evolución perpetua. Llena tu espacio con su encanto distintivo. Sumérgete en el mágico mundo de los Filodendros de Hoja de Corazón.",
        lm: "Sombra",
        size: "Chica",
        price: 2999,
        image: "../assets/img/plants/filodendro-hoja-corazon.jpg",
        quantity: 1
    },
]